spring.application.name=demo

#Connexion à la base de données
spring.datasource.url=jdbc:sqlserver://localhost;databasename=DEMO_ENI_ECOLE;integratedSecurity=false;encrypt=false;trustServerCertificate=false
spring.datasource.username=sa
spring.datasource.password=Pa$$w0rd

#Détail des requêtes pour le développement
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=create
